//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTest.WCF
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Currency", Namespace="http://www.webserviceX.NET/")]
    public enum Currency : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DZD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AWG = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BSD = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BHD = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BDT = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BBD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BZD = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMD = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTN = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOB = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BWP = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BRL = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GBP = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BND = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIF = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XOF = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAF = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KHR = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAD = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CVE = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KYD = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLP = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNY = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COP = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KMF = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRC = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRK = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUP = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CYP = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CZK = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DKK = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DJF = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOP = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XCD = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGP = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVC = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EEK = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETB = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUR = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FKP = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMD = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GHC = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIP = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAU = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GTQ = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GNF = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GYD = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTG = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HNL = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HKD = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HUF = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISK = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INR = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDR = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IQD = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILS = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JMD = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPY = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JOD = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KZT = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KES = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KRW = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KWD = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LAK = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LVL = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LBP = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LSL = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LRD = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LYD = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTL = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOP = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MKD = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGF = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MWK = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MYR = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MVR = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTL = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MRO = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUR = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXN = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MDL = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNT = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAD = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MZM = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MMK = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NAD = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NPR = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANG = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NZD = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIO = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NGN = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KPW = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOK = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMR = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPF = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PKR = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPD = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAB = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PGK = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PYG = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PEN = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHP = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPT = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLN = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QAR = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROL = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUB = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WST = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STD = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAR = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCR = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SLL = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAG = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SGD = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SKK = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIT = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SBD = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOS = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZAR = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LKR = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHP = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDD = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SRG = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SZL = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEK = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHF = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYP = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TWD = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TZS = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THB = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOP = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TTD = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TND = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRL = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USD = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AED = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UGX = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UAH = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UYU = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VUV = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VEB = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VND = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YER = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YUM = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZMK = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZWD = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRY = 150,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET/", ConfigurationName="JobTest.WCF.CurrencyConvertorSoap")]
    public interface CurrencyConvertorSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ConversionRate", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ConversionRateAsync(JobTest.WCF.Currency FromCurrency, JobTest.WCF.Currency ToCurrency);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public interface CurrencyConvertorSoapChannel : JobTest.WCF.CurrencyConvertorSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public partial class CurrencyConvertorSoapClient : System.ServiceModel.ClientBase<JobTest.WCF.CurrencyConvertorSoap>, JobTest.WCF.CurrencyConvertorSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CurrencyConvertorSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CurrencyConvertorSoapClient.GetBindingForEndpoint(endpointConfiguration), CurrencyConvertorSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CurrencyConvertorSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CurrencyConvertorSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CurrencyConvertorSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CurrencyConvertorSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CurrencyConvertorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> ConversionRateAsync(JobTest.WCF.Currency FromCurrency, JobTest.WCF.Currency ToCurrency)
        {
            return base.Channel.ConversionRateAsync(FromCurrency, ToCurrency);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CurrencyConvertorSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CurrencyConvertorSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CurrencyConvertorSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.webservicex.net/currencyconvertor.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CurrencyConvertorSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.webservicex.net/currencyconvertor.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CurrencyConvertorSoap,
            
            CurrencyConvertorSoap12,
        }
    }
}
